
services:
  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - MINIO_HOST=minio
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=admin123
      - BACKEND_PORT=${BACKEND_PORT}

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
       - FRONTEND_PORT=${FRONTEND_PORT}
       - BACKEND_URL=http://backend:${BACKEND_PORT}    
       - MINIO_HOST=minio
       - MINIO_PORT=${MINIO_PORT}
    depends_on:
      - backend

  minio:
    image: minio/minio
    ports:
      - "${MINIO_PORT}:${MINIO_PORT}"
      - "${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"
    volumes:
      - minio_data:/data

volumes:
  minio_data:


